# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nounou-dit-tout.com
title: Nounou dit tout
email: shane.vaudrey@gmail.com
author: Shane VAUDREY
description: > # "Write an awesome description for your new site here.
  Nounou-dit-tout is the essential tool for childminders and babysitters. Simplify the management of your working hours and invoicing using our intuitive application. Our platform makes it easy to calculate billable hours, while offering total transparency to parents, who can check recorded hours at any time. In addition to streamlining invoicing, Nounou-dit-tout also facilitates seamless digital exchanges between childcare professionals and families, making communication more efficient than ever before.
copyright: 'Copyright &copy; 2015 Shane Vaudrey. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Shane35300/
  - title: linkedin
    url: https://www.linkedin.com/in/shane-vaudrey/
