# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nounou-dit-tout.com
title: nounou-dit-tout
email: shane.vaudrey@gmail.com
author: Shane VAUDREY
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Shane35300/
  - title: linkedin
    url: https://www.linkedin.com/in/shane-vaudrey/
